// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AggregatedStats struct {
	_tab flatbuffers.Table
}

func GetRootAsAggregatedStats(buf []byte, offset flatbuffers.UOffsetT) *AggregatedStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AggregatedStats{}
	x.Init(buf, n+offset)
	return x
}

func FinishAggregatedStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAggregatedStats(buf []byte, offset flatbuffers.UOffsetT) *AggregatedStats {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AggregatedStats{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAggregatedStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AggregatedStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AggregatedStats) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AggregatedStats) TotalGames() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalGames(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AggregatedStats) Player0Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer0Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *AggregatedStats) Player1Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer1Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *AggregatedStats) Draws() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateDraws(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *AggregatedStats) AvgTurns() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AggregatedStats) MutateAvgTurns(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *AggregatedStats) MedianTurns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateMedianTurns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *AggregatedStats) AvgDurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateAvgDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *AggregatedStats) Errors() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateErrors(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *AggregatedStats) Wins(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *AggregatedStats) WinsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AggregatedStats) MutateWins(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *AggregatedStats) PlayerCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayerCount(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *AggregatedStats) TotalDecisions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalDecisions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *AggregatedStats) TotalValidMoves() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalValidMoves(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *AggregatedStats) ForcedDecisions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateForcedDecisions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func (rcv *AggregatedStats) TotalHandSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalHandSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(30, n)
}

func (rcv *AggregatedStats) TotalInteractions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalInteractions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(32, n)
}

func (rcv *AggregatedStats) TotalActions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalActions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(34, n)
}

func (rcv *AggregatedStats) TotalClaims() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalClaims(n uint64) bool {
	return rcv._tab.MutateUint64Slot(36, n)
}

func (rcv *AggregatedStats) TotalBluffs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalBluffs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(38, n)
}

func (rcv *AggregatedStats) TotalChallenges() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalChallenges(n uint64) bool {
	return rcv._tab.MutateUint64Slot(40, n)
}

func (rcv *AggregatedStats) SuccessfulBluffs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateSuccessfulBluffs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(42, n)
}

func (rcv *AggregatedStats) SuccessfulCatches() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateSuccessfulCatches(n uint64) bool {
	return rcv._tab.MutateUint64Slot(44, n)
}

func (rcv *AggregatedStats) TotalBets() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalBets(n uint64) bool {
	return rcv._tab.MutateUint64Slot(46, n)
}

func (rcv *AggregatedStats) BettingBluffs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateBettingBluffs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(48, n)
}

func (rcv *AggregatedStats) FoldWins() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateFoldWins(n uint64) bool {
	return rcv._tab.MutateUint64Slot(50, n)
}

func (rcv *AggregatedStats) ShowdownWins() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(52))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateShowdownWins(n uint64) bool {
	return rcv._tab.MutateUint64Slot(52, n)
}

func (rcv *AggregatedStats) AllInCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(54))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateAllInCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(54, n)
}

func (rcv *AggregatedStats) LeadChanges() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(56))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateLeadChanges(n uint32) bool {
	return rcv._tab.MutateUint32Slot(56, n)
}

func (rcv *AggregatedStats) DecisiveTurnPct() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(58))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *AggregatedStats) MutateDecisiveTurnPct(n float32) bool {
	return rcv._tab.MutateFloat32Slot(58, n)
}

func (rcv *AggregatedStats) ClosestMargin() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(60))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *AggregatedStats) MutateClosestMargin(n float32) bool {
	return rcv._tab.MutateFloat32Slot(60, n)
}

func (rcv *AggregatedStats) TrailingWinners() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(62))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTrailingWinners(n uint32) bool {
	return rcv._tab.MutateUint32Slot(62, n)
}

func (rcv *AggregatedStats) MoveDisruptionEvents() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(64))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateMoveDisruptionEvents(n uint64) bool {
	return rcv._tab.MutateUint64Slot(64, n)
}

func (rcv *AggregatedStats) ContentionEvents() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(66))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateContentionEvents(n uint64) bool {
	return rcv._tab.MutateUint64Slot(66, n)
}

func (rcv *AggregatedStats) ForcedResponseEvents() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(68))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateForcedResponseEvents(n uint64) bool {
	return rcv._tab.MutateUint64Slot(68, n)
}

func (rcv *AggregatedStats) OpponentTurnCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(70))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateOpponentTurnCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(70, n)
}

func AggregatedStatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(34)
}
func AggregatedStatsAddTotalGames(builder *flatbuffers.Builder, totalGames uint32) {
	builder.PrependUint32Slot(0, totalGames, 0)
}
func AggregatedStatsAddPlayer0Wins(builder *flatbuffers.Builder, player0Wins uint32) {
	builder.PrependUint32Slot(1, player0Wins, 0)
}
func AggregatedStatsAddPlayer1Wins(builder *flatbuffers.Builder, player1Wins uint32) {
	builder.PrependUint32Slot(2, player1Wins, 0)
}
func AggregatedStatsAddDraws(builder *flatbuffers.Builder, draws uint32) {
	builder.PrependUint32Slot(3, draws, 0)
}
func AggregatedStatsAddAvgTurns(builder *flatbuffers.Builder, avgTurns float32) {
	builder.PrependFloat32Slot(4, avgTurns, 0.0)
}
func AggregatedStatsAddMedianTurns(builder *flatbuffers.Builder, medianTurns uint32) {
	builder.PrependUint32Slot(5, medianTurns, 0)
}
func AggregatedStatsAddAvgDurationNs(builder *flatbuffers.Builder, avgDurationNs uint64) {
	builder.PrependUint64Slot(6, avgDurationNs, 0)
}
func AggregatedStatsAddErrors(builder *flatbuffers.Builder, errors uint32) {
	builder.PrependUint32Slot(7, errors, 0)
}
func AggregatedStatsAddWins(builder *flatbuffers.Builder, wins flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(wins), 0)
}
func AggregatedStatsStartWinsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AggregatedStatsAddPlayerCount(builder *flatbuffers.Builder, playerCount byte) {
	builder.PrependByteSlot(9, playerCount, 0)
}
func AggregatedStatsAddTotalDecisions(builder *flatbuffers.Builder, totalDecisions uint64) {
	builder.PrependUint64Slot(10, totalDecisions, 0)
}
func AggregatedStatsAddTotalValidMoves(builder *flatbuffers.Builder, totalValidMoves uint64) {
	builder.PrependUint64Slot(11, totalValidMoves, 0)
}
func AggregatedStatsAddForcedDecisions(builder *flatbuffers.Builder, forcedDecisions uint64) {
	builder.PrependUint64Slot(12, forcedDecisions, 0)
}
func AggregatedStatsAddTotalHandSize(builder *flatbuffers.Builder, totalHandSize uint64) {
	builder.PrependUint64Slot(13, totalHandSize, 0)
}
func AggregatedStatsAddTotalInteractions(builder *flatbuffers.Builder, totalInteractions uint64) {
	builder.PrependUint64Slot(14, totalInteractions, 0)
}
func AggregatedStatsAddTotalActions(builder *flatbuffers.Builder, totalActions uint64) {
	builder.PrependUint64Slot(15, totalActions, 0)
}
func AggregatedStatsAddTotalClaims(builder *flatbuffers.Builder, totalClaims uint64) {
	builder.PrependUint64Slot(16, totalClaims, 0)
}
func AggregatedStatsAddTotalBluffs(builder *flatbuffers.Builder, totalBluffs uint64) {
	builder.PrependUint64Slot(17, totalBluffs, 0)
}
func AggregatedStatsAddTotalChallenges(builder *flatbuffers.Builder, totalChallenges uint64) {
	builder.PrependUint64Slot(18, totalChallenges, 0)
}
func AggregatedStatsAddSuccessfulBluffs(builder *flatbuffers.Builder, successfulBluffs uint64) {
	builder.PrependUint64Slot(19, successfulBluffs, 0)
}
func AggregatedStatsAddSuccessfulCatches(builder *flatbuffers.Builder, successfulCatches uint64) {
	builder.PrependUint64Slot(20, successfulCatches, 0)
}
func AggregatedStatsAddTotalBets(builder *flatbuffers.Builder, totalBets uint64) {
	builder.PrependUint64Slot(21, totalBets, 0)
}
func AggregatedStatsAddBettingBluffs(builder *flatbuffers.Builder, bettingBluffs uint64) {
	builder.PrependUint64Slot(22, bettingBluffs, 0)
}
func AggregatedStatsAddFoldWins(builder *flatbuffers.Builder, foldWins uint64) {
	builder.PrependUint64Slot(23, foldWins, 0)
}
func AggregatedStatsAddShowdownWins(builder *flatbuffers.Builder, showdownWins uint64) {
	builder.PrependUint64Slot(24, showdownWins, 0)
}
func AggregatedStatsAddAllInCount(builder *flatbuffers.Builder, allInCount uint64) {
	builder.PrependUint64Slot(25, allInCount, 0)
}
func AggregatedStatsAddLeadChanges(builder *flatbuffers.Builder, leadChanges uint32) {
	builder.PrependUint32Slot(26, leadChanges, 0)
}
func AggregatedStatsAddDecisiveTurnPct(builder *flatbuffers.Builder, decisiveTurnPct float32) {
	builder.PrependFloat32Slot(27, decisiveTurnPct, 1.0)
}
func AggregatedStatsAddClosestMargin(builder *flatbuffers.Builder, closestMargin float32) {
	builder.PrependFloat32Slot(28, closestMargin, 1.0)
}
func AggregatedStatsAddTrailingWinners(builder *flatbuffers.Builder, trailingWinners uint32) {
	builder.PrependUint32Slot(29, trailingWinners, 0)
}
func AggregatedStatsAddMoveDisruptionEvents(builder *flatbuffers.Builder, moveDisruptionEvents uint64) {
	builder.PrependUint64Slot(30, moveDisruptionEvents, 0)
}
func AggregatedStatsAddContentionEvents(builder *flatbuffers.Builder, contentionEvents uint64) {
	builder.PrependUint64Slot(31, contentionEvents, 0)
}
func AggregatedStatsAddForcedResponseEvents(builder *flatbuffers.Builder, forcedResponseEvents uint64) {
	builder.PrependUint64Slot(32, forcedResponseEvents, 0)
}
func AggregatedStatsAddOpponentTurnCount(builder *flatbuffers.Builder, opponentTurnCount uint64) {
	builder.PrependUint64Slot(33, opponentTurnCount, 0)
}
func AggregatedStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
