// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AggregatedStats struct {
	_tab flatbuffers.Table
}

func GetRootAsAggregatedStats(buf []byte, offset flatbuffers.UOffsetT) *AggregatedStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AggregatedStats{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AggregatedStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AggregatedStats) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AggregatedStats) TotalGames() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalGames(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AggregatedStats) Player0Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer0Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *AggregatedStats) Player1Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer1Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *AggregatedStats) Draws() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateDraws(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *AggregatedStats) AvgTurns() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AggregatedStats) MutateAvgTurns(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *AggregatedStats) MedianTurns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateMedianTurns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *AggregatedStats) AvgDurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateAvgDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *AggregatedStats) Errors() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateErrors(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *AggregatedStats) Wins(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *AggregatedStats) WinsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AggregatedStats) MutateWins(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *AggregatedStats) PlayerCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayerCount(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *AggregatedStats) TotalDecisions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalDecisions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *AggregatedStats) TotalValidMoves() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalValidMoves(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *AggregatedStats) ForcedDecisions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateForcedDecisions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func (rcv *AggregatedStats) TotalHandSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalHandSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(30, n)
}

func (rcv *AggregatedStats) TotalInteractions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalInteractions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(32, n)
}

func (rcv *AggregatedStats) TotalActions() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalActions(n uint64) bool {
	return rcv._tab.MutateUint64Slot(34, n)
}

func (rcv *AggregatedStats) TotalClaims() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalClaims(n uint64) bool {
	return rcv._tab.MutateUint64Slot(36, n)
}

func (rcv *AggregatedStats) TotalBluffs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalBluffs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(38, n)
}

func (rcv *AggregatedStats) TotalChallenges() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalChallenges(n uint64) bool {
	return rcv._tab.MutateUint64Slot(40, n)
}

func (rcv *AggregatedStats) SuccessfulBluffs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateSuccessfulBluffs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(42, n)
}

func (rcv *AggregatedStats) SuccessfulCatches() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateSuccessfulCatches(n uint64) bool {
	return rcv._tab.MutateUint64Slot(44, n)
}

func (rcv *AggregatedStats) AvgFinalChips(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *AggregatedStats) AvgFinalChipsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AggregatedStats) MutateAvgFinalChips(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *AggregatedStats) FoldRate() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AggregatedStats) MutateFoldRate(n float32) bool {
	return rcv._tab.MutateFloat32Slot(48, n)
}

func (rcv *AggregatedStats) TotalPotsWon() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalPotsWon(n uint64) bool {
	return rcv._tab.MutateUint64Slot(50, n)
}

func AggregatedStatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(24)
}
func AggregatedStatsAddTotalGames(builder *flatbuffers.Builder, totalGames uint32) {
	builder.PrependUint32Slot(0, totalGames, 0)
}
func AggregatedStatsAddPlayer0Wins(builder *flatbuffers.Builder, player0Wins uint32) {
	builder.PrependUint32Slot(1, player0Wins, 0)
}
func AggregatedStatsAddPlayer1Wins(builder *flatbuffers.Builder, player1Wins uint32) {
	builder.PrependUint32Slot(2, player1Wins, 0)
}
func AggregatedStatsAddDraws(builder *flatbuffers.Builder, draws uint32) {
	builder.PrependUint32Slot(3, draws, 0)
}
func AggregatedStatsAddAvgTurns(builder *flatbuffers.Builder, avgTurns float32) {
	builder.PrependFloat32Slot(4, avgTurns, 0.0)
}
func AggregatedStatsAddMedianTurns(builder *flatbuffers.Builder, medianTurns uint32) {
	builder.PrependUint32Slot(5, medianTurns, 0)
}
func AggregatedStatsAddAvgDurationNs(builder *flatbuffers.Builder, avgDurationNs uint64) {
	builder.PrependUint64Slot(6, avgDurationNs, 0)
}
func AggregatedStatsAddErrors(builder *flatbuffers.Builder, errors uint32) {
	builder.PrependUint32Slot(7, errors, 0)
}
func AggregatedStatsAddWins(builder *flatbuffers.Builder, wins flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(wins), 0)
}
func AggregatedStatsStartWinsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AggregatedStatsAddPlayerCount(builder *flatbuffers.Builder, playerCount byte) {
	builder.PrependByteSlot(9, playerCount, 0)
}
func AggregatedStatsAddTotalDecisions(builder *flatbuffers.Builder, totalDecisions uint64) {
	builder.PrependUint64Slot(10, totalDecisions, 0)
}
func AggregatedStatsAddTotalValidMoves(builder *flatbuffers.Builder, totalValidMoves uint64) {
	builder.PrependUint64Slot(11, totalValidMoves, 0)
}
func AggregatedStatsAddForcedDecisions(builder *flatbuffers.Builder, forcedDecisions uint64) {
	builder.PrependUint64Slot(12, forcedDecisions, 0)
}
func AggregatedStatsAddTotalHandSize(builder *flatbuffers.Builder, totalHandSize uint64) {
	builder.PrependUint64Slot(13, totalHandSize, 0)
}
func AggregatedStatsAddTotalInteractions(builder *flatbuffers.Builder, totalInteractions uint64) {
	builder.PrependUint64Slot(14, totalInteractions, 0)
}
func AggregatedStatsAddTotalActions(builder *flatbuffers.Builder, totalActions uint64) {
	builder.PrependUint64Slot(15, totalActions, 0)
}
func AggregatedStatsAddTotalClaims(builder *flatbuffers.Builder, totalClaims uint64) {
	builder.PrependUint64Slot(16, totalClaims, 0)
}
func AggregatedStatsAddTotalBluffs(builder *flatbuffers.Builder, totalBluffs uint64) {
	builder.PrependUint64Slot(17, totalBluffs, 0)
}
func AggregatedStatsAddTotalChallenges(builder *flatbuffers.Builder, totalChallenges uint64) {
	builder.PrependUint64Slot(18, totalChallenges, 0)
}
func AggregatedStatsAddSuccessfulBluffs(builder *flatbuffers.Builder, successfulBluffs uint64) {
	builder.PrependUint64Slot(19, successfulBluffs, 0)
}
func AggregatedStatsAddSuccessfulCatches(builder *flatbuffers.Builder, successfulCatches uint64) {
	builder.PrependUint64Slot(20, successfulCatches, 0)
}
func AggregatedStatsAddAvgFinalChips(builder *flatbuffers.Builder, avgFinalChips flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(21, flatbuffers.UOffsetT(avgFinalChips), 0)
}
func AggregatedStatsStartAvgFinalChipsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AggregatedStatsAddFoldRate(builder *flatbuffers.Builder, foldRate float32) {
	builder.PrependFloat32Slot(22, foldRate, 0.0)
}
func AggregatedStatsAddTotalPotsWon(builder *flatbuffers.Builder, totalPotsWon uint64) {
	builder.PrependUint64Slot(23, totalPotsWon, 0)
}
func AggregatedStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
