// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BatchRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsBatchRequest(buf []byte, offset flatbuffers.UOffsetT) *BatchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BatchRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishBatchRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBatchRequest(buf []byte, offset flatbuffers.UOffsetT) *BatchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BatchRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBatchRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BatchRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BatchRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BatchRequest) Requests(obj *SimulationRequest, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BatchRequest) RequestsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BatchRequest) BatchId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BatchRequest) MutateBatchId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func BatchRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BatchRequestAddRequests(builder *flatbuffers.Builder, requests flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requests), 0)
}
func BatchRequestStartRequestsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BatchRequestAddBatchId(builder *flatbuffers.Builder, batchId uint64) {
	builder.PrependUint64Slot(1, batchId, 0)
}
func BatchRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
