// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BatchResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsBatchResponse(buf []byte, offset flatbuffers.UOffsetT) *BatchResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BatchResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishBatchResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBatchResponse(buf []byte, offset flatbuffers.UOffsetT) *BatchResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BatchResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBatchResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BatchResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BatchResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BatchResponse) BatchId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BatchResponse) MutateBatchId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BatchResponse) Results(obj *AggregatedStats, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BatchResponse) ResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BatchResponse) TotalDurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BatchResponse) MutateTotalDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func BatchResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func BatchResponseAddBatchId(builder *flatbuffers.Builder, batchId uint64) {
	builder.PrependUint64Slot(0, batchId, 0)
}
func BatchResponseAddResults(builder *flatbuffers.Builder, results flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(results), 0)
}
func BatchResponseStartResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BatchResponseAddTotalDurationNs(builder *flatbuffers.Builder, totalDurationNs uint64) {
	builder.PrependUint64Slot(2, totalDurationNs, 0)
}
func BatchResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
