// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SimulationResult struct {
	_tab flatbuffers.Table
}

func GetRootAsSimulationResult(buf []byte, offset flatbuffers.UOffsetT) *SimulationResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SimulationResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishSimulationResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSimulationResult(buf []byte, offset flatbuffers.UOffsetT) *SimulationResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SimulationResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSimulationResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SimulationResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SimulationResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SimulationResult) Winner() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationResult) MutateWinner(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *SimulationResult) TotalTurns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationResult) MutateTotalTurns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SimulationResult) GameDurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationResult) MutateGameDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *SimulationResult) ErrorCode() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationResult) MutateErrorCode(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *SimulationResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SimulationResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SimulationResultAddWinner(builder *flatbuffers.Builder, winner int8) {
	builder.PrependInt8Slot(0, winner, 0)
}
func SimulationResultAddTotalTurns(builder *flatbuffers.Builder, totalTurns uint32) {
	builder.PrependUint32Slot(1, totalTurns, 0)
}
func SimulationResultAddGameDurationNs(builder *flatbuffers.Builder, gameDurationNs uint64) {
	builder.PrependUint64Slot(2, gameDurationNs, 0)
}
func SimulationResultAddErrorCode(builder *flatbuffers.Builder, errorCode byte) {
	builder.PrependByteSlot(3, errorCode, 0)
}
func SimulationResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(errorMessage), 0)
}
func SimulationResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
