// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SimulationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSimulationRequest(buf []byte, offset flatbuffers.UOffsetT) *SimulationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SimulationRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SimulationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SimulationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SimulationRequest) GenomeBytecode(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SimulationRequest) GenomeBytecodeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SimulationRequest) GenomeBytecodeBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SimulationRequest) MutateGenomeBytecode(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SimulationRequest) NumGames() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutateNumGames(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SimulationRequest) AiPlayerType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutateAiPlayerType(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *SimulationRequest) MctsIterations() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutateMctsIterations(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *SimulationRequest) RandomSeed() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutateRandomSeed(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *SimulationRequest) Player0AiType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutatePlayer0AiType(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *SimulationRequest) Player1AiType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutatePlayer1AiType(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *SimulationRequest) AiTypes(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SimulationRequest) AiTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SimulationRequest) AiTypesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SimulationRequest) MutateAiTypes(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SimulationRequest) PlayerCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutatePlayerCount(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *SimulationRequest) StartingChips() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SimulationRequest) MutateStartingChips(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func SimulationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func SimulationRequestAddGenomeBytecode(builder *flatbuffers.Builder, genomeBytecode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(genomeBytecode), 0)
}
func SimulationRequestStartGenomeBytecodeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SimulationRequestAddNumGames(builder *flatbuffers.Builder, numGames uint32) {
	builder.PrependUint32Slot(1, numGames, 0)
}
func SimulationRequestAddAiPlayerType(builder *flatbuffers.Builder, aiPlayerType byte) {
	builder.PrependByteSlot(2, aiPlayerType, 0)
}
func SimulationRequestAddMctsIterations(builder *flatbuffers.Builder, mctsIterations uint32) {
	builder.PrependUint32Slot(3, mctsIterations, 0)
}
func SimulationRequestAddRandomSeed(builder *flatbuffers.Builder, randomSeed uint64) {
	builder.PrependUint64Slot(4, randomSeed, 0)
}
func SimulationRequestAddPlayer0AiType(builder *flatbuffers.Builder, player0AiType byte) {
	builder.PrependByteSlot(5, player0AiType, 0)
}
func SimulationRequestAddPlayer1AiType(builder *flatbuffers.Builder, player1AiType byte) {
	builder.PrependByteSlot(6, player1AiType, 0)
}
func SimulationRequestAddAiTypes(builder *flatbuffers.Builder, aiTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(aiTypes), 0)
}
func SimulationRequestStartAiTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SimulationRequestAddPlayerCount(builder *flatbuffers.Builder, playerCount byte) {
	builder.PrependByteSlot(8, playerCount, 0)
}
func SimulationRequestAddStartingChips(builder *flatbuffers.Builder, startingChips uint32) {
	builder.PrependUint32Slot(9, startingChips, 0)
}
func SimulationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
