// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TeamAssignment struct {
	_tab flatbuffers.Table
}

func GetRootAsTeamAssignment(buf []byte, offset flatbuffers.UOffsetT) *TeamAssignment {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TeamAssignment{}
	x.Init(buf, n+offset)
	return x
}

func FinishTeamAssignmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTeamAssignment(buf []byte, offset flatbuffers.UOffsetT) *TeamAssignment {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TeamAssignment{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTeamAssignmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TeamAssignment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TeamAssignment) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TeamAssignment) PlayerIndices(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TeamAssignment) PlayerIndicesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TeamAssignment) PlayerIndicesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TeamAssignment) MutatePlayerIndices(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func TeamAssignmentStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TeamAssignmentAddPlayerIndices(builder *flatbuffers.Builder, playerIndices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(playerIndices), 0)
}
func TeamAssignmentStartPlayerIndicesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TeamAssignmentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
