package evolution

import (
	"math/rand/v2"
	"testing"

	"github.com/darwindeck/darwindeck/pkg/genome"
	"github.com/darwindeck/darwindeck/pkg/mechanic"
)

// hookedMechanics is the set of borrows that actually affect the outcome:
// either a WORKING hook in mechanic.BuildHooks (the banking borrows) OR a
// runner-side implementation that changes the move set or win condition (the
// DEEP borrows MechRunPlay/MechFollowSuit/MechKnock, consulted inside the
// shedding runner). The cross-family paths may only emit these -- a borrow with
// neither is inert and lies in the rulebook. (MechTrump / MechPlayMultiple are
// reserved enum values with no implementation.)
var hookedMechanics = map[genome.MechanicType]bool{
	genome.MechTrickScoring: true,
	genome.MechMeldBonus:    true,
	genome.MechDrawPenalty:  true,
	genome.MechAvoidance:    true,
	genome.MechRunPlay:      true,
	genome.MechFollowSuit:   true,
	genome.MechKnock:        true,
}

// TestCrossFamilyBorrowsAreWhitelistedAndHooked: every (host, other) pair the
// engine can cross must yield only borrows that are (a) in the validBorrows
// whitelist for the host and (b) backed by a working hook. This is the
// valid-in/valid-out + no-inert-borrow guard for the diversified matrix.
func TestCrossFamilyBorrowsAreWhitelistedAndHooked(t *testing.T) {
	rng := rand.New(rand.NewPCG(1, 2))
	whitelist := genome.ValidBorrows()
	skeletons := []genome.SkeletonType{genome.Shedding, genome.TrickTaking, genome.Rummy, genome.Casino, genome.Climbing, genome.Vying}

	for _, host := range skeletons {
		allowed := make(map[genome.MechanicType]bool)
		for _, m := range whitelist[host] {
			allowed[m] = true
		}
		for _, other := range skeletons {
			if other == host {
				continue
			}
			// Sample many draws to exercise the random pick.
			for i := 0; i < 200; i++ {
				bm, ok := crossFamilyBorrow(host, other, rng)
				if !ok {
					continue
				}
				if bm.Source == host {
					t.Fatalf("host=%v other=%v: borrow Source must differ from host (self-borrow rejected by validation), got %v", host, other, bm.Source)
				}
				if !allowed[bm.Mechanic] {
					t.Fatalf("host=%v other=%v: produced non-whitelisted borrow %v", host, other, bm.Mechanic)
				}
				if !hookedMechanics[bm.Mechanic] {
					t.Fatalf("host=%v other=%v: produced un-hooked (inert) borrow %v", host, other, bm.Mechanic)
				}
			}
		}
	}
}

// ungeneratedBorrows lists (host, mechanic) combinations that are WHITELISTED
// (valid if a genome already carries them, and covered by the fire+mutate
// integration test) but deliberately NOT GENERATED by the engine, because the
// borrow cannot be made OUTCOME-SIGNIFICANT on that host (Wave-3): its hook
// fires too rarely under play to ever decide the winner, so generating it would
// only manufacture vestigial hybrids -- the exact Wave-2 failure this wave
// removes. Mirrors the climbing precedent (only the borrow that can get teeth is
// generated). Keep this in lockstep with the candidate tables in
// crossFamilyBorrow and addBorrowedMechanic.
//
//   - rummy + trick_scoring: rummy "captures" are laid-down melds, which random
//     play almost never forms before knock/gin, so applyTrickScoring's capture
//     bonus is essentially never banked -- a vestigial tally.
var ungeneratedBorrows = map[genome.SkeletonType]map[genome.MechanicType]bool{
	genome.Rummy: {genome.MechTrickScoring: true},
}

// TestCrossFamilyBorrowReachesFullWhitelist is the DIVERSITY assertion: across
// the legal cross partners, each host's crossFamilyBorrow must be able to reach
// every mechanic the whitelist permits for that host EXCEPT the documented
// ungeneratable dead combos -- otherwise a host family is structurally barred
// from novel territory it CAN reach (the Wave-1 trap where only
// trick+meld+avoidance got crossed and shedding/rummy hosts produced zero novel
// games). A combo listed in ungeneratedBorrows must NOT be reached (it would be
// vestigial); every other whitelisted combo must be reachable.
func TestCrossFamilyBorrowReachesFullWhitelist(t *testing.T) {
	rng := rand.New(rand.NewPCG(99, 7))
	whitelist := genome.ValidBorrows()
	skeletons := []genome.SkeletonType{genome.Shedding, genome.TrickTaking, genome.Rummy, genome.Casino, genome.Climbing, genome.Vying}
	// Cross partners include Climbing: crossover can pair any two skeletons, and
	// some cross-family borrows are sourced from climbing (e.g. MechRunPlay's
	// multi-card combinations borrowed onto a shedding host). Omitting climbing
	// as a partner would make such borrows look unreachable when they enter via
	// a shedding x climbing pairing.
	partners := []genome.SkeletonType{genome.Shedding, genome.TrickTaking, genome.Rummy, genome.Climbing}

	for _, host := range skeletons {
		reached := make(map[genome.MechanicType]bool)
		for _, other := range partners {
			if other == host {
				continue
			}
			for i := 0; i < 500; i++ {
				if bm, ok := crossFamilyBorrow(host, other, rng); ok {
					reached[bm.Mechanic] = true
				}
			}
		}
		for _, want := range whitelist[host] {
			if ungeneratedBorrows[host][want] {
				if reached[want] {
					t.Errorf("host=%v: crossFamilyBorrow generated %v, which is documented ungeneratable (vestigial-by-host)", host, want)
				}
				continue
			}
			if !reached[want] {
				t.Errorf("host=%v: crossFamilyBorrow never reached whitelisted mechanic %v across any cross partner", host, want)
			}
		}
	}
}

// TestHybridCrossoverEveryHostPairValidInValidOut walks every ordered pair of
// DIFFERENT-skeleton seeds, builds a hybrid, and requires the child to pass
// genome.Validate. Covers the diversified matrix end to end: shedding/rummy
// hosts must produce valid hybrids, not just trick hosts.
func TestHybridCrossoverEveryHostPairValidInValidOut(t *testing.T) {
	rng := rand.New(rand.NewPCG(5, 11))
	seeds := allSeeds()
	for _, a := range seeds {
		for _, b := range seeds {
			if a.Skeleton == b.Skeleton {
				continue
			}
			for i := 0; i < 25; i++ {
				child := hybridCrossover(a, b, rng)
				if child == nil {
					t.Fatalf("hybridCrossover(%s,%s) returned nil", a.ID, b.ID)
				}
				child.ID = "test-hybrid"
				if errs := genome.Validate(child); len(errs) > 0 {
					t.Fatalf("hybridCrossover(%s host, %s other) produced invalid child: %v", a.ID, b.ID, errs)
				}
				// Any borrow on the child must be hooked (no inert rules).
				for _, bm := range child.Borrowed {
					if !hookedMechanics[bm.Mechanic] {
						t.Fatalf("hybrid child carries un-hooked borrow %v (host %s)", bm.Mechanic, a.ID)
					}
				}
				// Hooks must actually build for the child (sanity: the borrow
				// is wired through the single hook-construction site).
				_ = mechanic.HooksFor(child)
			}
		}
	}
}

// TestRummyHostReachesDrawPenalty is the targeted regression for the specific
// Wave-1 gap this change closes: a rummy host crossed with a shedding parent
// must be able to borrow draw_penalty (a whitelisted, hooked mechanic that the
// pre-Wave-2 crossFamilyBorrow table omitted entirely).
func TestRummyHostReachesDrawPenalty(t *testing.T) {
	rng := rand.New(rand.NewPCG(3, 4))
	got := false
	for i := 0; i < 2000; i++ {
		if bm, ok := crossFamilyBorrow(genome.Rummy, genome.Shedding, rng); ok && bm.Mechanic == genome.MechDrawPenalty {
			got = true
			break
		}
	}
	if !got {
		t.Fatal("rummy host crossed with shedding never reached draw_penalty borrow (Wave-2 diversity gap)")
	}
}
