# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class BatchRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBatchRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchRequest()
        x.Init(buf, n + offset)
        return x

    # BatchRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchRequest
    def Requests(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .SimulationRequest import SimulationRequest
            obj = SimulationRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchRequest
    def RequestsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchRequest
    def BatchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def BatchRequestStart(builder): builder.StartObject(2)
def BatchRequestAddRequests(builder, requests): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requests), 0)
def BatchRequestStartRequestsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BatchRequestAddBatchId(builder, batchId): builder.PrependUint64Slot(1, batchId, 0)
def BatchRequestEnd(builder): return builder.EndObject()
