# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class AggregatedStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAggregatedStats(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AggregatedStats()
        x.Init(buf, n + offset)
        return x

    # AggregatedStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AggregatedStats
    def TotalGames(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Player0Wins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Player1Wins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Draws(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def AvgTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AggregatedStats
    def MedianTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def AvgDurationNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Errors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalDecisions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalValidMoves(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def ForcedDecisions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalInteractions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalActions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AggregatedStatsStart(builder): builder.StartObject(13)
def AggregatedStatsAddTotalGames(builder, totalGames): builder.PrependUint32Slot(0, totalGames, 0)
def AggregatedStatsAddPlayer0Wins(builder, player0Wins): builder.PrependUint32Slot(1, player0Wins, 0)
def AggregatedStatsAddPlayer1Wins(builder, player1Wins): builder.PrependUint32Slot(2, player1Wins, 0)
def AggregatedStatsAddDraws(builder, draws): builder.PrependUint32Slot(3, draws, 0)
def AggregatedStatsAddAvgTurns(builder, avgTurns): builder.PrependFloat32Slot(4, avgTurns, 0.0)
def AggregatedStatsAddMedianTurns(builder, medianTurns): builder.PrependUint32Slot(5, medianTurns, 0)
def AggregatedStatsAddAvgDurationNs(builder, avgDurationNs): builder.PrependUint64Slot(6, avgDurationNs, 0)
def AggregatedStatsAddErrors(builder, errors): builder.PrependUint32Slot(7, errors, 0)
def AggregatedStatsAddTotalDecisions(builder, totalDecisions): builder.PrependUint64Slot(8, totalDecisions, 0)
def AggregatedStatsAddTotalValidMoves(builder, totalValidMoves): builder.PrependUint64Slot(9, totalValidMoves, 0)
def AggregatedStatsAddForcedDecisions(builder, forcedDecisions): builder.PrependUint64Slot(10, forcedDecisions, 0)
def AggregatedStatsAddTotalInteractions(builder, totalInteractions): builder.PrependUint64Slot(11, totalInteractions, 0)
def AggregatedStatsAddTotalActions(builder, totalActions): builder.PrependUint64Slot(12, totalActions, 0)
def AggregatedStatsEnd(builder): return builder.EndObject()
