# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class AggregatedStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAggregatedStats(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AggregatedStats()
        x.Init(buf, n + offset)
        return x

    # AggregatedStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AggregatedStats
    def TotalGames(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Player0Wins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Player1Wins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Draws(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def AvgTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AggregatedStats
    def MedianTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def AvgDurationNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Errors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def Wins(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AggregatedStats
    def WinsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # AggregatedStats
    def WinsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AggregatedStats
    def PlayerCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalDecisions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalValidMoves(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def ForcedDecisions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalHandSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalInteractions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalActions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalClaims(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalBluffs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def TotalChallenges(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def SuccessfulBluffs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def SuccessfulCatches(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AggregatedStats
    def AvgFinalChips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AggregatedStats
    def AvgFinalChipsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # AggregatedStats
    def AvgFinalChipsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AggregatedStats
    def FoldRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AggregatedStats
    def TotalPotsWon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AggregatedStatsStart(builder): builder.StartObject(24)
def AggregatedStatsAddTotalGames(builder, totalGames): builder.PrependUint32Slot(0, totalGames, 0)
def AggregatedStatsAddPlayer0Wins(builder, player0Wins): builder.PrependUint32Slot(1, player0Wins, 0)
def AggregatedStatsAddPlayer1Wins(builder, player1Wins): builder.PrependUint32Slot(2, player1Wins, 0)
def AggregatedStatsAddDraws(builder, draws): builder.PrependUint32Slot(3, draws, 0)
def AggregatedStatsAddAvgTurns(builder, avgTurns): builder.PrependFloat32Slot(4, avgTurns, 0.0)
def AggregatedStatsAddMedianTurns(builder, medianTurns): builder.PrependUint32Slot(5, medianTurns, 0)
def AggregatedStatsAddAvgDurationNs(builder, avgDurationNs): builder.PrependUint64Slot(6, avgDurationNs, 0)
def AggregatedStatsAddErrors(builder, errors): builder.PrependUint32Slot(7, errors, 0)
def AggregatedStatsAddWins(builder, wins): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(wins), 0)
def AggregatedStatsStartWinsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AggregatedStatsAddPlayerCount(builder, playerCount): builder.PrependUint8Slot(9, playerCount, 0)
def AggregatedStatsAddTotalDecisions(builder, totalDecisions): builder.PrependUint64Slot(10, totalDecisions, 0)
def AggregatedStatsAddTotalValidMoves(builder, totalValidMoves): builder.PrependUint64Slot(11, totalValidMoves, 0)
def AggregatedStatsAddForcedDecisions(builder, forcedDecisions): builder.PrependUint64Slot(12, forcedDecisions, 0)
def AggregatedStatsAddTotalHandSize(builder, totalHandSize): builder.PrependUint64Slot(13, totalHandSize, 0)
def AggregatedStatsAddTotalInteractions(builder, totalInteractions): builder.PrependUint64Slot(14, totalInteractions, 0)
def AggregatedStatsAddTotalActions(builder, totalActions): builder.PrependUint64Slot(15, totalActions, 0)
def AggregatedStatsAddTotalClaims(builder, totalClaims): builder.PrependUint64Slot(16, totalClaims, 0)
def AggregatedStatsAddTotalBluffs(builder, totalBluffs): builder.PrependUint64Slot(17, totalBluffs, 0)
def AggregatedStatsAddTotalChallenges(builder, totalChallenges): builder.PrependUint64Slot(18, totalChallenges, 0)
def AggregatedStatsAddSuccessfulBluffs(builder, successfulBluffs): builder.PrependUint64Slot(19, successfulBluffs, 0)
def AggregatedStatsAddSuccessfulCatches(builder, successfulCatches): builder.PrependUint64Slot(20, successfulCatches, 0)
def AggregatedStatsAddAvgFinalChips(builder, avgFinalChips): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(avgFinalChips), 0)
def AggregatedStatsStartAvgFinalChipsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AggregatedStatsAddFoldRate(builder, foldRate): builder.PrependFloat32Slot(22, foldRate, 0.0)
def AggregatedStatsAddTotalPotsWon(builder, totalPotsWon): builder.PrependUint64Slot(23, totalPotsWon, 0)
def AggregatedStatsEnd(builder): return builder.EndObject()
