# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class BatchResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBatchResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchResponse()
        x.Init(buf, n + offset)
        return x

    # BatchResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchResponse
    def BatchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BatchResponse
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .AggregatedStats import AggregatedStats
            obj = AggregatedStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchResponse
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchResponse
    def TotalDurationNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def BatchResponseStart(builder): builder.StartObject(3)
def BatchResponseAddBatchId(builder, batchId): builder.PrependUint64Slot(0, batchId, 0)
def BatchResponseAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def BatchResponseStartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BatchResponseAddTotalDurationNs(builder, totalDurationNs): builder.PrependUint64Slot(2, totalDurationNs, 0)
def BatchResponseEnd(builder): return builder.EndObject()
