# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class SimulationRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimulationRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimulationRequest()
        x.Init(buf, n + offset)
        return x

    # SimulationRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimulationRequest
    def GenomeBytecode(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SimulationRequest
    def GenomeBytecodeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SimulationRequest
    def GenomeBytecodeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SimulationRequest
    def NumGames(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SimulationRequest
    def AiPlayerType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SimulationRequest
    def MctsIterations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SimulationRequest
    def RandomSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def SimulationRequestStart(builder): builder.StartObject(5)
def SimulationRequestAddGenomeBytecode(builder, genomeBytecode): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(genomeBytecode), 0)
def SimulationRequestStartGenomeBytecodeVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def SimulationRequestAddNumGames(builder, numGames): builder.PrependUint32Slot(1, numGames, 0)
def SimulationRequestAddAiPlayerType(builder, aiPlayerType): builder.PrependUint8Slot(2, aiPlayerType, 0)
def SimulationRequestAddMctsIterations(builder, mctsIterations): builder.PrependUint32Slot(3, mctsIterations, 0)
def SimulationRequestAddRandomSeed(builder, randomSeed): builder.PrependUint64Slot(4, randomSeed, 0)
def SimulationRequestEnd(builder): return builder.EndObject()
