# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers

class SimulationResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimulationResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimulationResult()
        x.Init(buf, n + offset)
        return x

    # SimulationResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimulationResult
    def Winner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SimulationResult
    def TotalTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SimulationResult
    def GameDurationNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SimulationResult
    def ErrorCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SimulationResult
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SimulationResultStart(builder): builder.StartObject(5)
def SimulationResultAddWinner(builder, winner): builder.PrependInt8Slot(0, winner, 0)
def SimulationResultAddTotalTurns(builder, totalTurns): builder.PrependUint32Slot(1, totalTurns, 0)
def SimulationResultAddGameDurationNs(builder, gameDurationNs): builder.PrependUint64Slot(2, gameDurationNs, 0)
def SimulationResultAddErrorCode(builder, errorCode): builder.PrependUint8Slot(3, errorCode, 0)
def SimulationResultAddErrorMessage(builder, errorMessage): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)
def SimulationResultEnd(builder): return builder.EndObject()
