# automatically generated by the FlatBuffers compiler, do not modify

# namespace: cardsim

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TeamAssignment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TeamAssignment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTeamAssignment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TeamAssignment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TeamAssignment
    def PlayerIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TeamAssignment
    def PlayerIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TeamAssignment
    def PlayerIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TeamAssignment
    def PlayerIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TeamAssignmentStart(builder):
    builder.StartObject(1)

def Start(builder):
    TeamAssignmentStart(builder)

def TeamAssignmentAddPlayerIndices(builder, playerIndices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(playerIndices), 0)

def AddPlayerIndices(builder, playerIndices):
    TeamAssignmentAddPlayerIndices(builder, playerIndices)

def TeamAssignmentStartPlayerIndicesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPlayerIndicesVector(builder, numElems):
    return TeamAssignmentStartPlayerIndicesVector(builder, numElems)

def TeamAssignmentEnd(builder):
    return builder.EndObject()

def End(builder):
    return TeamAssignmentEnd(builder)
